# GitHub Action Labeler v5 yapılandırma dosyası

example_change:
  - changed-files:
    - any-glob-to-any-file: 'example/**'

example2_change:
  - changed-files:
    - any-glob-to-any-file: 'example2/*'

text_files:
  - changed-files:
    - any-glob-to-any-file: '**/*.txt'
